version: '3.8'
services:
  ai-data-agent:
    build: .
    container_name: ai-data-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: python main.py