version: '3.8'
services:
  ai-data-agent:
    build: .
    container_name: ai-data-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: python main.py
    depends_on:
      - ollama
    environment:
      - LLM_ENDPOINT=http://ollama:11434/api/generate
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # Labels for log identification
    labels:
      - "logging.level=debug"
      - "service.name=ai-data-agent"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: serve
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  ollama_data: